package org.openrndr.svg

internal object Elements {
    const val Circle = "circle"
    const val Defs = "defs"
    const val Ellipse = "ellipse"
    const val Font = "font"
    const val FontFace = "font-face"
    const val FontFaceSrc = "font-face-src"
    const val FontFaceUri = "font-face-uri"
    const val G = "g"
    const val Image = "image"
    const val Line = "line"
    const val LinearGradient = "linearGradient"
    const val Path = "path"
    const val Polygon = "polygon"
    const val Polyline = "polyline"
    const val RadialGradient = "radialGradient"
    const val Rect = "rect"
    const val SolidColor = "solidColor"
    const val Stop = "stop"
    const val Svg = "svg"
    const val Switch = "switch"
    const val Tbreak = "tbreak"
    const val Text = "text"
    const val TextArea = "textArea"
    const val Title = "title"
    const val Tspan = "tspan"
    const val Use = "use"
}

/**
 * Contains both attributes and properties but the difference is merely semantic.
 */
internal object Attributes {
    const val BaseProfile = "baseProfile"
    const val Class = "class"
    const val Color = "color"
    const val ColorRendering = "color-rendering"
    const val Cx = "cx"
    const val Cy = "cy"
    const val D = "d"
    const val Direction = "direction"
    const val Display = "display"
    const val DisplayAlign = "display-align"
    const val Dx = "dx"
    const val Dy = "dy"
    const val Fill = "fill"
    const val FillOpacity = "fill-opacity"
    const val FillRule = "fill-rule"
    const val FontFamily = "font-family"
    const val FontSize = "font-size"
    const val FontStyle = "font-style"
    const val FontVariant = "font-variant"
    const val FontWeight = "font-weight"
    const val GradientUnits = "gradientUnits"
    const val Height = "height"
    const val Href = "href"
    const val Id = "id"
    const val ImageRendering = "image-rendering"
    const val LineIncrement = "line-increment"
    const val Offset = "offset"
    const val Opacity = "opacity"
    const val PathLength = "pathLength"
    const val Points = "points"
    const val PreserveAspectRatio = "preserveAspectRatio"
    const val R = "r"
    const val RequiredExtensions = "requiredExtensions"
    const val RequiredFeatures = "requiredFeatures"
    const val RequiredFonts = "requiredFonts"
    const val RequiredFormats = "requiredFormats"
    const val Rotate = "rotate"
    const val Rx = "rx"
    const val Ry = "ry"
    const val ShapeRendering = "shape-rendering"
    const val SolidColor = "solid-color"
    const val SolidOpacity = "solid-opacity"
    const val Space = "space"
    const val StopColor = "stop-color"
    const val StopOpacity = "stop-opacity"
    const val Stroke = "stroke"
    const val StrokeDasharray = "stroke-dasharray"
    const val StrokeDashoffset = "stroke-dashoffset"
    const val StrokeLinecap = "stroke-linecap"
    const val StrokeLinejoin = "stroke-linejoin"
    const val StrokeMiterlimit = "stroke-miterlimit"
    const val StrokeOpacity = "stroke-opacity"
    const val StrokeWidth = "stroke-width"
    const val Style = "style"
    const val SystemLanguage = "system-language"
    const val TextAlign = "text-align"
    const val TextAnchor = "text-anchor"
    const val TextRendering = "text-rendering"
    const val Title = "title"
    const val Transform = "transform"
    const val Version = "version"
    const val ViewBox = "viewBox"
    const val ViewportFill = "viewport-fill"
    const val ViewportFillOpacity = "viewport-fill-opacity"
    const val Visibility = "visibility"
    const val Width = "width"
    const val X = "x"
    const val X1 = "x1"
    const val X2 = "x2"
    const val Y = "y"
    const val Y1 = "y1"
    const val Y2 = "y2"
}